name: Actions Tester

# on:
#   workflow_dispatch:
on:
  push:
    branches: [test]

jobs:
  send:
    name: Test JWT generator
    runs-on: ubuntu-latest
    steps:
      # checkout repo to use local action
      - name: Checkout
        uses: actions/checkout@v2
      # use local action
      - name: JWT Generator
        id: jwtGenerator
        uses: ./
        with:
          secret: topSecret
          payload: '{"hello":"world"}'
          options: '{"expiresIn":"5m"}'
          envVar: SOME_OUTPUT_ENV_VAR
      - name: DUMP Token
        run: echo $SOME_OUTPUT_ENV_VAR
